# Generated by Django 3.2.8 on 2023-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='sent_at',
            new_name='sent_date',
        ),
        migrations.RemoveField(
            model_name='email',
            name='opened_at',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sent',
        ),
        migrations.AddField(
            model_name='email',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
